#Gitlab CI YAML for building latex
image: gitlab.mrt.uni-karlsruhe.de:21443/mrt/misc/mrt_build/latex:latest

compile_pdf:
  script:
    # compile pdf
    - latexmk -pdf
  artifacts:
    paths:
      - root.pdf
