#Gitlab CI YAML for building latex
image: gitlab.mrt.kit.edu:21443/mrt/misc/mrt_build/latex:latest

compile_pdf:
  script:
    # compile pdf
    - latexmk --shell-escape -pdf
  artifacts:
    paths:
      - root.pdf
